services:
  caddy:
    image: "caddy:2.8.4-alpine"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/data

  postgres:
    image: "bitnami/postgresql:16"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=todos
    volumes:
      - "postgres_data:/bitnami/postgresql"

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - SERVER_DEBUG=False
      - SERVER_ENVIRONMENT=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - SERVER_LOG_LEVEL=INFO
      - SERVER_CORS_ALLOW_ORIGINS=["http://localhost", "http://127.0.0.1", "https://localhost", "https://127.0.0.1"]
      - SERVER_DATABASE_URL=postgresql+asyncpg://user:pass@postgres:5432/todos
      - SERVER_DATABASE_POOL_SIZE=20
      - SERVER_ROOT_PATH="/api"
    depends_on:
      - postgres

  client:
    image: client
    build:
      context: ./client
    environment:
      NODE_ENV: production
      VITE_API_URL: "https://localhost/api/graphql"
    ports:
      - 3000:3000
    depends_on:
      - server

volumes:
  postgres_data:
  caddy_config:
